version: "3"

services:
  api:
    build:
      context: ./services/test-birdie-api/
    ports:
      - "3000:3000"
    volumes:
      - ./services/test-birdie-api/:/home/app
  
  frontend:
    build:
      context: ./services/test-birdie-frontend/
    ports:
      - "4200:4200"
    volumes:
      - ./services/test-birdie-frontend/:/var/www
    depends_on:
      - api
    environment:
      - PORT=4200
